/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BasicDetail: typeof import('./src/components/BasicDetail/index.vue')['default']
    Connect: typeof import('./src/components/Connect/index.vue')['default']
    Feed: typeof import('./src/components/Feed/index.vue')['default']
  }
}
